### ISSUE TITLE
How do you decide when and how to split a library from its parent project?

### ISSUE THREAD

**Issue by javajosh** [jart/json.cpp#9]
Hi Justine, not really an issue more of a question. Long-time fan of your work starting with redbean and contuing now with llamafile and your various other works. This library looks nice and minimal and fast, which seem to be your hallmarks! This "issue" is more about a question of taste and judgement regarding when and how you choose to separate out a library and distribute separately. Clearly you've chosen to do this now, 2 years after writing it. BTW I think this is the correct way to write general deps: use them yourself then "graduate" them to their own project. But why now? And also, does it increase your administrative overhead in the original project to now have a separate repo/build for a dependency? What is your cost/benefit analysis of this? For example, one signal that a lib is ready for mitosis is that it's very stable, hasn't changed in quite a while? Then of course there is the risk that once split others will want to change it to be more general and invalidate or complicate the original use case! Your ownership of this repo mitigates this of course, but it seems like an interesting problem to have, especially when "minimalism" is a core attribute. 

Feel free to close unanswered because I know you're busy making great stuff, but I wanted to pick your brain if you're willing. (I'm facing something similar and am probably overthinking it!)

**Comment by jart** [comment]
A lot of the stuff I build is wedded to Cosmopolitan Libc. Every now and then, I build something that's easy to cleanly separate from the whole and make portable to other compilers. Whenever I see the opportunity to do that, I try to take it, since it broadens the impact of my work, and helps a broader audience benefit from it. Anything I break out, I usually like for it to be focused, near its final form, understandable, and difficult to improve upon. json.cpp isn't an endless project like cosmopolitan that can keep me shuffling off my mortal coil for years. But it's cool, and having an independent repo for it gives me a platform to explain a cool component that's worth specific attention. It costs me little. It's better than writing a blog piece about an individual piece of cosmopolitan, since there's something you can more easily hold in your hands here. Use it with Cosmopolitan or don't. So, similar to projects like bestline and jtckdint, I hope you get ample enjoyment out of it!
